//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ou_Department
    {
        public Ou_Department()
        {
            this.Ou_Role = new HashSet<Ou_Role>();
            this.Ou_UserInfo = new HashSet<Ou_UserInfo>();
        }
    
        public int depId { get; set; }
        public int depPid { get; set; }
        public string depName { get; set; }
        public string depRemark { get; set; }
        public bool depIsDel { get; set; }
        public System.DateTime depAddTime { get; set; }
    
        public virtual ICollection<Ou_Role> Ou_Role { get; set; }
        public virtual ICollection<Ou_UserInfo> Ou_UserInfo { get; set; }
    }
}
