//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ou_Permission
    {
        public Ou_Permission()
        {
            this.Ou_RolePermission = new HashSet<Ou_RolePermission>();
            this.Ou_UserVipPermission = new HashSet<Ou_UserVipPermission>();
        }
    
        public int pid { get; set; }
        public int pParent { get; set; }
        public string pName { get; set; }
        public string pAreaName { get; set; }
        public string pControllerName { get; set; }
        public string pActionName { get; set; }
        public short pFormMethod { get; set; }
        public short pOperationType { get; set; }
        public string pIco { get; set; }
        public int pOrder { get; set; }
        public bool pIsLink { get; set; }
        public string pLinkUrl { get; set; }
        public bool pIsShow { get; set; }
        public string pRemark { get; set; }
        public bool pIsDel { get; set; }
        public System.DateTime pAddTime { get; set; }
    
        public virtual ICollection<Ou_RolePermission> Ou_RolePermission { get; set; }
        public virtual ICollection<Ou_UserVipPermission> Ou_UserVipPermission { get; set; }
    }
}
