//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ou_Role
    {
        public Ou_Role()
        {
            this.Ou_RolePermission = new HashSet<Ou_RolePermission>();
            this.Ou_UserRole = new HashSet<Ou_UserRole>();
        }
    
        public int rId { get; set; }
        public int rDepId { get; set; }
        public string rName { get; set; }
        public string rRemark { get; set; }
        public bool rIsShow { get; set; }
        public bool rIsDel { get; set; }
        public System.DateTime rAddTime { get; set; }
    
        public virtual Ou_Department Ou_Department { get; set; }
        public virtual ICollection<Ou_RolePermission> Ou_RolePermission { get; set; }
        public virtual ICollection<Ou_UserRole> Ou_UserRole { get; set; }
    }
}
