//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ou_UserInfo
    {
        public Ou_UserInfo()
        {
            this.Ou_UserRole = new HashSet<Ou_UserRole>();
            this.Ou_UserVipPermission = new HashSet<Ou_UserVipPermission>();
        }
    
        public int uId { get; set; }
        public int uDepId { get; set; }
        public string uLoginName { get; set; }
        public string uPwd { get; set; }
        public bool uGender { get; set; }
        public string uPost { get; set; }
        public string uRemark { get; set; }
        public bool uIsDel { get; set; }
        public System.DateTime uAddTime { get; set; }
    
        public virtual Ou_Department Ou_Department { get; set; }
        public virtual ICollection<Ou_UserRole> Ou_UserRole { get; set; }
        public virtual ICollection<Ou_UserVipPermission> Ou_UserVipPermission { get; set; }
    }
}
