//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ou_UserVipPermission
    {
        public int vipId { get; set; }
        public int vipUserId { get; set; }
        public int vipPermission { get; set; }
        public string vipRemark { get; set; }
        public bool vipIsDel { get; set; }
        public System.DateTime vipAddTime { get; set; }
    
        public virtual Ou_Permission Ou_Permission { get; set; }
        public virtual Ou_UserInfo Ou_UserInfo { get; set; }
    }
}
