//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ou_UserRole
    {
        public int urId { get; set; }
        public int urUId { get; set; }
        public int urRId { get; set; }
        public bool urIsDel { get; set; }
        public System.DateTime urAddtime { get; set; }
    
        public virtual Ou_Role Ou_Role { get; set; }
        public virtual Ou_UserInfo Ou_UserInfo { get; set; }
    }
}
