//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OuOAEntities : DbContext
    {
        public OuOAEntities()
            : base("name=OuOAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bill_Leave> Bill_Leave { get; set; }
        public virtual DbSet<Ou_Department> Ou_Department { get; set; }
        public virtual DbSet<Ou_Permission> Ou_Permission { get; set; }
        public virtual DbSet<Ou_Role> Ou_Role { get; set; }
        public virtual DbSet<Ou_RolePermission> Ou_RolePermission { get; set; }
        public virtual DbSet<Ou_UserInfo> Ou_UserInfo { get; set; }
        public virtual DbSet<Ou_UserRole> Ou_UserRole { get; set; }
        public virtual DbSet<Ou_UserVipPermission> Ou_UserVipPermission { get; set; }
        public virtual DbSet<WF_AutoTransactNode> WF_AutoTransactNode { get; set; }
        public virtual DbSet<WF_BillFlowNode> WF_BillFlowNode { get; set; }
        public virtual DbSet<WF_BillFlowNodeRemark> WF_BillFlowNodeRemark { get; set; }
        public virtual DbSet<WF_BillState> WF_BillState { get; set; }
        public virtual DbSet<WF_Node> WF_Node { get; set; }
        public virtual DbSet<WF_NodeState> WF_NodeState { get; set; }
        public virtual DbSet<WF_WorkFlow> WF_WorkFlow { get; set; }
        public virtual DbSet<WF_WorkFlowNode> WF_WorkFlowNode { get; set; }
    }
}
