//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_AutoTransactNode
    {
        public int AutoTransactNodeID { get; set; }
        public Nullable<int> WorkFlowNodeID { get; set; }
    
        public virtual WF_WorkFlowNode WF_WorkFlowNode { get; set; }
    }
}
