//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_BillState
    {
        public WF_BillState()
        {
            this.Bill_Leave = new HashSet<Bill_Leave>();
        }
    
        public int BillStateID { get; set; }
        public string BillStateName { get; set; }
    
        public virtual ICollection<Bill_Leave> Bill_Leave { get; set; }
    }
}
