//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_NodeState
    {
        public WF_NodeState()
        {
            this.WF_BillFlowNode = new HashSet<WF_BillFlowNode>();
        }
    
        public int NodeStateID { get; set; }
        public string NodeStateName { get; set; }
    
        public virtual ICollection<WF_BillFlowNode> WF_BillFlowNode { get; set; }
    }
}
