//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_WorkFlowNode
    {
        public WF_WorkFlowNode()
        {
            this.WF_AutoTransactNode = new HashSet<WF_AutoTransactNode>();
            this.WF_BillFlowNode = new HashSet<WF_BillFlowNode>();
        }
    
        public int WorkFlowNodeID { get; set; }
        public Nullable<int> WorkFlowID { get; set; }
        public Nullable<int> NodeID { get; set; }
        public Nullable<int> WorkFlowNodeSequence { get; set; }
        public string Remark { get; set; }
    
        public virtual ICollection<WF_AutoTransactNode> WF_AutoTransactNode { get; set; }
        public virtual ICollection<WF_BillFlowNode> WF_BillFlowNode { get; set; }
        public virtual WF_Node WF_Node { get; set; }
        public virtual WF_WorkFlow WF_WorkFlow { get; set; }
    }
}
